name: On Pull Request

on: pull_request

jobs:
  build_linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo fmt --check
          cargo clippy
          cargo test
          cargo test --release
          cargo doc

  build_macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo fmt --check
          cargo clippy
          cargo test
          cargo test --release
          cargo doc

  build_windows:
    name: Build on Windows (stub)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build
